<?php

namespace Intracto\SecretSantaBundle\Tests;

use Intracto\SecretSantaBundle\Entity\Entry;
use Intracto\SecretSantaBundle\Entity\EntryShuffler;
use Intracto\SecretSantaBundle\Entity\Pool;

class EntryShufflerTest extends \PHPUnit_Framework_TestCase
{
    public function testEntryShufflerCase1()
    {
        $pool = new Pool();
        foreach ($pool->getEntries() as $defaultEntry) {
            $pool->removeEntry($defaultEntry);
        }

        $entry1 = new Entry();
        $entry1->setName('Entry 1');
        $pool->addEntrie($entry1);

        $entry2 = new Entry();
        $entry2->setName('Entry 2');
        $pool->addEntrie($entry2);

        $entry3 = new Entry();
        $entry3->setName('Entry 3');
        $pool->addEntrie($entry3);

        $entry4 = new Entry();
        $entry4->setName('Entry 4');
        $pool->addEntrie($entry4);

        $entry1->addExcludedEntry($entry2);
        $entry2->addExcludedEntry($entry3);
        $entry4->addExcludedEntry($entry1);
        $entry4->addExcludedEntry($entry2);

        $entryShuffler = new EntryShuffler();
        for ($i = 0; $i < 1000; $i++) {
            $shuffeledEntries = $entryShuffler->shuffleEntries($pool);

            $key = 0;
            foreach ($pool->getEntries() as $entry) {
                //check if we did not match excluded entry
                $this->assertNotContains($shuffeledEntries[$key], $entry->getExcludedEntries());
                //check if we have an entry matched
                $this->assertNotNull($shuffeledEntries[$key]);
                $key++;
            }
        }
    }

    public function testEntryShufflerCase2()
    {
        $pool = new Pool();
        foreach ($pool->getEntries() as $defaultEntry) {
            $pool->removeEntry($defaultEntry);
        }

        $fam0entry0 = new Entry();
        $fam0entry0->setName('Fam 0 Entry 0');
        $pool->addEntrie($fam0entry0);
        $fam0entry1 = new Entry();
        $fam0entry1->setName('Fam 0 Entry 1');
        $pool->addEntrie($fam0entry1);
        $fam0entry2 = new Entry();
        $fam0entry2->setName('Fam 0 Entry 2');
        $pool->addEntrie($fam0entry2);
        $fam0entry3 = new Entry();
        $fam0entry3->setName('Fam 0 Entry 3');
        $pool->addEntrie($fam0entry3);
        $fam0entry4 = new Entry();
        $fam0entry4->setName('Fam 0 Entry 4');
        $pool->addEntrie($fam0entry4);
        $fam0entry5 = new Entry();
        $fam0entry5->setName('Fam 0 Entry 5');
        $pool->addEntrie($fam0entry5);
        $fam0entry6 = new Entry();
        $fam0entry6->setName('Fam 0 Entry 6');
        $pool->addEntrie($fam0entry6);
        $fam0entry7 = new Entry();
        $fam0entry7->setName('Fam 0 Entry 7');
        $pool->addEntrie($fam0entry7);
        $fam0entry8 = new Entry();
        $fam0entry8->setName('Fam 0 Entry 8');
        $pool->addEntrie($fam0entry8);
        $fam0entry9 = new Entry();
        $fam0entry9->setName('Fam 0 Entry 9');
        $pool->addEntrie($fam0entry9);

        $fam1entry0 = new Entry();
        $fam1entry0->setName('Fam 1 Entry 0');
        $pool->addEntrie($fam1entry0);
        $fam1entry1 = new Entry();
        $fam1entry1->setName('Fam 1 Entry 1');
        $pool->addEntrie($fam1entry1);
        $fam1entry2 = new Entry();
        $fam1entry2->setName('Fam 1 Entry 2');
        $pool->addEntrie($fam1entry2);
        $fam1entry3 = new Entry();
        $fam1entry3->setName('Fam 1 Entry 3');
        $pool->addEntrie($fam1entry3);
        $fam1entry4 = new Entry();
        $fam1entry4->setName('Fam 1 Entry 4');
        $pool->addEntrie($fam1entry4);
        $fam1entry5 = new Entry();
        $fam1entry5->setName('Fam 1 Entry 5');
        $pool->addEntrie($fam1entry5);
        $fam1entry6 = new Entry();
        $fam1entry6->setName('Fam 1 Entry 6');
        $pool->addEntrie($fam1entry6);
        $fam1entry7 = new Entry();
        $fam1entry7->setName('Fam 1 Entry 7');
        $pool->addEntrie($fam1entry7);
        $fam1entry8 = new Entry();
        $fam1entry8->setName('Fam 1 Entry 8');
        $pool->addEntrie($fam1entry8);
        $fam1entry9 = new Entry();
        $fam1entry9->setName('Fam 1 Entry 9');
        $pool->addEntrie($fam1entry9);

        $fam2entry0 = new Entry();
        $fam2entry0->setName('Fam 2 Entry 0');
        $pool->addEntrie($fam2entry0);
        $fam2entry1 = new Entry();
        $fam2entry1->setName('Fam 2 Entry 1');
        $pool->addEntrie($fam2entry1);
        $fam2entry2 = new Entry();
        $fam2entry2->setName('Fam 2 Entry 2');
        $pool->addEntrie($fam2entry2);
        $fam2entry3 = new Entry();
        $fam2entry3->setName('Fam 2 Entry 3');
        $pool->addEntrie($fam2entry3);
        $fam2entry4 = new Entry();
        $fam2entry4->setName('Fam 2 Entry 4');
        $pool->addEntrie($fam2entry4);
        $fam2entry5 = new Entry();
        $fam2entry5->setName('Fam 2 Entry 5');
        $pool->addEntrie($fam2entry5);
        $fam2entry6 = new Entry();
        $fam2entry6->setName('Fam 2 Entry 6');
        $pool->addEntrie($fam2entry6);
        $fam2entry7 = new Entry();
        $fam2entry7->setName('Fam 2 Entry 7');
        $pool->addEntrie($fam2entry7);
        $fam2entry8 = new Entry();
        $fam2entry8->setName('Fam 2 Entry 8');
        $pool->addEntrie($fam2entry8);
        $fam2entry9 = new Entry();
        $fam2entry9->setName('Fam 2 Entry 9');
        $pool->addEntrie($fam2entry9);

        $fam3entry0 = new Entry();
        $fam3entry0->setName('Fam 3 Entry 0');
        $pool->addEntrie($fam3entry0);
        $fam3entry1 = new Entry();
        $fam3entry1->setName('Fam 3 Entry 1');
        $pool->addEntrie($fam3entry1);
        $fam3entry2 = new Entry();
        $fam3entry2->setName('Fam 3 Entry 2');
        $pool->addEntrie($fam3entry2);
        $fam3entry3 = new Entry();
        $fam3entry3->setName('Fam 3 Entry 3');
        $pool->addEntrie($fam3entry3);
        $fam3entry4 = new Entry();
        $fam3entry4->setName('Fam 3 Entry 4');
        $pool->addEntrie($fam3entry4);
        $fam3entry5 = new Entry();
        $fam3entry5->setName('Fam 3 Entry 5');
        $pool->addEntrie($fam3entry5);
        $fam3entry6 = new Entry();
        $fam3entry6->setName('Fam 3 Entry 6');
        $pool->addEntrie($fam3entry6);
        $fam3entry7 = new Entry();
        $fam3entry7->setName('Fam 3 Entry 7');
        $pool->addEntrie($fam3entry7);
        $fam3entry8 = new Entry();
        $fam3entry8->setName('Fam 3 Entry 8');
        $pool->addEntrie($fam3entry8);
        $fam3entry9 = new Entry();
        $fam3entry9->setName('Fam 3 Entry 9');
        $pool->addEntrie($fam3entry9);

        $fam4entry0 = new Entry();
        $fam4entry0->setName('Fam 4 Entry 0');
        $pool->addEntrie($fam4entry0);
        $fam4entry1 = new Entry();
        $fam4entry1->setName('Fam 4 Entry 1');
        $pool->addEntrie($fam4entry1);
        $fam4entry2 = new Entry();
        $fam4entry2->setName('Fam 4 Entry 2');
        $pool->addEntrie($fam4entry2);
        $fam4entry3 = new Entry();
        $fam4entry3->setName('Fam 4 Entry 3');
        $pool->addEntrie($fam4entry3);
        $fam4entry4 = new Entry();
        $fam4entry4->setName('Fam 4 Entry 4');
        $pool->addEntrie($fam4entry4);
        $fam4entry5 = new Entry();
        $fam4entry5->setName('Fam 4 Entry 5');
        $pool->addEntrie($fam4entry5);
        $fam4entry6 = new Entry();
        $fam4entry6->setName('Fam 4 Entry 6');
        $pool->addEntrie($fam4entry6);
        $fam4entry7 = new Entry();
        $fam4entry7->setName('Fam 4 Entry 7');
        $pool->addEntrie($fam4entry7);
        $fam4entry8 = new Entry();
        $fam4entry8->setName('Fam 4 Entry 8');
        $pool->addEntrie($fam4entry8);
        $fam4entry9 = new Entry();
        $fam4entry9->setName('Fam 4 Entry 9');
        $pool->addEntrie($fam4entry9);

        $fam5entry0 = new Entry();
        $fam5entry0->setName('Fam 5 Entry 0');
        $pool->addEntrie($fam5entry0);
        $fam5entry1 = new Entry();
        $fam5entry1->setName('Fam 5 Entry 1');
        $pool->addEntrie($fam5entry1);
        $fam5entry2 = new Entry();
        $fam5entry2->setName('Fam 5 Entry 2');
        $pool->addEntrie($fam5entry2);
        $fam5entry3 = new Entry();
        $fam5entry3->setName('Fam 5 Entry 3');
        $pool->addEntrie($fam5entry3);
        $fam5entry4 = new Entry();
        $fam5entry4->setName('Fam 5 Entry 4');
        $pool->addEntrie($fam5entry4);
        $fam5entry5 = new Entry();
        $fam5entry5->setName('Fam 5 Entry 5');
        $pool->addEntrie($fam5entry5);
        $fam5entry6 = new Entry();
        $fam5entry6->setName('Fam 5 Entry 6');
        $pool->addEntrie($fam5entry6);
        $fam5entry7 = new Entry();
        $fam5entry7->setName('Fam 5 Entry 7');
        $pool->addEntrie($fam5entry7);
        $fam5entry8 = new Entry();
        $fam5entry8->setName('Fam 5 Entry 8');
        $pool->addEntrie($fam5entry8);
        $fam5entry9 = new Entry();
        $fam5entry9->setName('Fam 5 Entry 9');
        $pool->addEntrie($fam5entry9);

        $fam6entry0 = new Entry();
        $fam6entry0->setName('Fam 6 Entry 0');
        $pool->addEntrie($fam6entry0);
        $fam6entry1 = new Entry();
        $fam6entry1->setName('Fam 6 Entry 1');
        $pool->addEntrie($fam6entry1);
        $fam6entry2 = new Entry();
        $fam6entry2->setName('Fam 6 Entry 2');
        $pool->addEntrie($fam6entry2);
        $fam6entry3 = new Entry();
        $fam6entry3->setName('Fam 6 Entry 3');
        $pool->addEntrie($fam6entry3);
        $fam6entry4 = new Entry();
        $fam6entry4->setName('Fam 6 Entry 4');
        $pool->addEntrie($fam6entry4);
        $fam6entry5 = new Entry();
        $fam6entry5->setName('Fam 6 Entry 5');
        $pool->addEntrie($fam6entry5);
        $fam6entry6 = new Entry();
        $fam6entry6->setName('Fam 6 Entry 6');
        $pool->addEntrie($fam6entry6);
        $fam6entry7 = new Entry();
        $fam6entry7->setName('Fam 6 Entry 7');
        $pool->addEntrie($fam6entry7);
        $fam6entry8 = new Entry();
        $fam6entry8->setName('Fam 6 Entry 8');
        $pool->addEntrie($fam6entry8);
        $fam6entry9 = new Entry();
        $fam6entry9->setName('Fam 6 Entry 9');
        $pool->addEntrie($fam6entry9);

        $fam7entry0 = new Entry();
        $fam7entry0->setName('Fam 7 Entry 0');
        $pool->addEntrie($fam7entry0);
        $fam7entry1 = new Entry();
        $fam7entry1->setName('Fam 7 Entry 1');
        $pool->addEntrie($fam7entry1);
        $fam7entry2 = new Entry();
        $fam7entry2->setName('Fam 7 Entry 2');
        $pool->addEntrie($fam7entry2);
        $fam7entry3 = new Entry();
        $fam7entry3->setName('Fam 7 Entry 3');
        $pool->addEntrie($fam7entry3);
        $fam7entry4 = new Entry();
        $fam7entry4->setName('Fam 7 Entry 4');
        $pool->addEntrie($fam7entry4);
        $fam7entry5 = new Entry();
        $fam7entry5->setName('Fam 7 Entry 5');
        $pool->addEntrie($fam7entry5);
        $fam7entry6 = new Entry();
        $fam7entry6->setName('Fam 7 Entry 6');
        $pool->addEntrie($fam7entry6);
        $fam7entry7 = new Entry();
        $fam7entry7->setName('Fam 7 Entry 7');
        $pool->addEntrie($fam7entry7);
        $fam7entry8 = new Entry();
        $fam7entry8->setName('Fam 7 Entry 8');
        $pool->addEntrie($fam7entry8);
        $fam7entry9 = new Entry();
        $fam7entry9->setName('Fam 7 Entry 9');
        $pool->addEntrie($fam7entry9);

        $fam8entry0 = new Entry();
        $fam8entry0->setName('Fam 8 Entry 0');
        $pool->addEntrie($fam8entry0);
        $fam8entry1 = new Entry();
        $fam8entry1->setName('Fam 8 Entry 1');
        $pool->addEntrie($fam8entry1);
        $fam8entry2 = new Entry();
        $fam8entry2->setName('Fam 8 Entry 2');
        $pool->addEntrie($fam8entry2);
        $fam8entry3 = new Entry();
        $fam8entry3->setName('Fam 8 Entry 3');
        $pool->addEntrie($fam8entry3);
        $fam8entry4 = new Entry();
        $fam8entry4->setName('Fam 8 Entry 4');
        $pool->addEntrie($fam8entry4);
        $fam8entry5 = new Entry();
        $fam8entry5->setName('Fam 8 Entry 5');
        $pool->addEntrie($fam8entry5);
        $fam8entry6 = new Entry();
        $fam8entry6->setName('Fam 8 Entry 6');
        $pool->addEntrie($fam8entry6);
        $fam8entry7 = new Entry();
        $fam8entry7->setName('Fam 8 Entry 7');
        $pool->addEntrie($fam8entry7);
        $fam8entry8 = new Entry();
        $fam8entry8->setName('Fam 8 Entry 8');
        $pool->addEntrie($fam8entry8);
        $fam8entry9 = new Entry();
        $fam8entry9->setName('Fam 8 Entry 9');
        $pool->addEntrie($fam8entry9);

        $fam9entry0 = new Entry();
        $fam9entry0->setName('Fam 9 Entry 0');
        $pool->addEntrie($fam9entry0);
        $fam9entry1 = new Entry();
        $fam9entry1->setName('Fam 9 Entry 1');
        $pool->addEntrie($fam9entry1);
        $fam9entry2 = new Entry();
        $fam9entry2->setName('Fam 9 Entry 2');
        $pool->addEntrie($fam9entry2);
        $fam9entry3 = new Entry();
        $fam9entry3->setName('Fam 9 Entry 3');
        $pool->addEntrie($fam9entry3);
        $fam9entry4 = new Entry();
        $fam9entry4->setName('Fam 9 Entry 4');
        $pool->addEntrie($fam9entry4);
        $fam9entry5 = new Entry();
        $fam9entry5->setName('Fam 9 Entry 5');
        $pool->addEntrie($fam9entry5);
        $fam9entry6 = new Entry();
        $fam9entry6->setName('Fam 9 Entry 6');
        $pool->addEntrie($fam9entry6);
        $fam9entry7 = new Entry();
        $fam9entry7->setName('Fam 9 Entry 7');
        $pool->addEntrie($fam9entry7);
        $fam9entry8 = new Entry();
        $fam9entry8->setName('Fam 9 Entry 8');
        $pool->addEntrie($fam9entry8);
        $fam9entry9 = new Entry();
        $fam9entry9->setName('Fam 9 Entry 9');
        $pool->addEntrie($fam9entry9);

        $fam0entry0->addExcludedEntry($fam0entry1);
        $fam0entry0->addExcludedEntry($fam0entry2);
        $fam0entry0->addExcludedEntry($fam0entry3);
        $fam0entry0->addExcludedEntry($fam0entry4);
        $fam0entry0->addExcludedEntry($fam0entry5);
        $fam0entry0->addExcludedEntry($fam0entry6);
        $fam0entry0->addExcludedEntry($fam0entry7);
        $fam0entry0->addExcludedEntry($fam0entry8);
        $fam0entry0->addExcludedEntry($fam0entry9);
        $fam0entry1->addExcludedEntry($fam0entry0);
        $fam0entry1->addExcludedEntry($fam0entry2);
        $fam0entry1->addExcludedEntry($fam0entry3);
        $fam0entry1->addExcludedEntry($fam0entry4);
        $fam0entry1->addExcludedEntry($fam0entry5);
        $fam0entry1->addExcludedEntry($fam0entry6);
        $fam0entry1->addExcludedEntry($fam0entry7);
        $fam0entry1->addExcludedEntry($fam0entry8);
        $fam0entry1->addExcludedEntry($fam0entry9);
        $fam0entry2->addExcludedEntry($fam0entry0);
        $fam0entry2->addExcludedEntry($fam0entry1);
        $fam0entry2->addExcludedEntry($fam0entry3);
        $fam0entry2->addExcludedEntry($fam0entry4);
        $fam0entry2->addExcludedEntry($fam0entry5);
        $fam0entry2->addExcludedEntry($fam0entry6);
        $fam0entry2->addExcludedEntry($fam0entry7);
        $fam0entry2->addExcludedEntry($fam0entry8);
        $fam0entry2->addExcludedEntry($fam0entry9);
        $fam0entry3->addExcludedEntry($fam0entry0);
        $fam0entry3->addExcludedEntry($fam0entry1);
        $fam0entry3->addExcludedEntry($fam0entry2);
        $fam0entry3->addExcludedEntry($fam0entry4);
        $fam0entry3->addExcludedEntry($fam0entry5);
        $fam0entry3->addExcludedEntry($fam0entry6);
        $fam0entry3->addExcludedEntry($fam0entry7);
        $fam0entry3->addExcludedEntry($fam0entry8);
        $fam0entry3->addExcludedEntry($fam0entry9);
        $fam0entry4->addExcludedEntry($fam0entry0);
        $fam0entry4->addExcludedEntry($fam0entry1);
        $fam0entry4->addExcludedEntry($fam0entry2);
        $fam0entry4->addExcludedEntry($fam0entry3);
        $fam0entry4->addExcludedEntry($fam0entry5);
        $fam0entry4->addExcludedEntry($fam0entry6);
        $fam0entry4->addExcludedEntry($fam0entry7);
        $fam0entry4->addExcludedEntry($fam0entry8);
        $fam0entry4->addExcludedEntry($fam0entry9);
        $fam0entry5->addExcludedEntry($fam0entry0);
        $fam0entry5->addExcludedEntry($fam0entry1);
        $fam0entry5->addExcludedEntry($fam0entry2);
        $fam0entry5->addExcludedEntry($fam0entry3);
        $fam0entry5->addExcludedEntry($fam0entry4);
        $fam0entry5->addExcludedEntry($fam0entry6);
        $fam0entry5->addExcludedEntry($fam0entry7);
        $fam0entry5->addExcludedEntry($fam0entry8);
        $fam0entry5->addExcludedEntry($fam0entry9);
        $fam0entry6->addExcludedEntry($fam0entry0);
        $fam0entry6->addExcludedEntry($fam0entry1);
        $fam0entry6->addExcludedEntry($fam0entry2);
        $fam0entry6->addExcludedEntry($fam0entry3);
        $fam0entry6->addExcludedEntry($fam0entry4);
        $fam0entry6->addExcludedEntry($fam0entry5);
        $fam0entry6->addExcludedEntry($fam0entry7);
        $fam0entry6->addExcludedEntry($fam0entry8);
        $fam0entry6->addExcludedEntry($fam0entry9);
        $fam0entry7->addExcludedEntry($fam0entry0);
        $fam0entry7->addExcludedEntry($fam0entry1);
        $fam0entry7->addExcludedEntry($fam0entry2);
        $fam0entry7->addExcludedEntry($fam0entry3);
        $fam0entry7->addExcludedEntry($fam0entry4);
        $fam0entry7->addExcludedEntry($fam0entry5);
        $fam0entry7->addExcludedEntry($fam0entry6);
        $fam0entry7->addExcludedEntry($fam0entry8);
        $fam0entry7->addExcludedEntry($fam0entry9);
        $fam0entry8->addExcludedEntry($fam0entry0);
        $fam0entry8->addExcludedEntry($fam0entry1);
        $fam0entry8->addExcludedEntry($fam0entry2);
        $fam0entry8->addExcludedEntry($fam0entry3);
        $fam0entry8->addExcludedEntry($fam0entry4);
        $fam0entry8->addExcludedEntry($fam0entry5);
        $fam0entry8->addExcludedEntry($fam0entry6);
        $fam0entry8->addExcludedEntry($fam0entry7);
        $fam0entry8->addExcludedEntry($fam0entry9);
        $fam0entry9->addExcludedEntry($fam0entry0);
        $fam0entry9->addExcludedEntry($fam0entry1);
        $fam0entry9->addExcludedEntry($fam0entry2);
        $fam0entry9->addExcludedEntry($fam0entry3);
        $fam0entry9->addExcludedEntry($fam0entry4);
        $fam0entry9->addExcludedEntry($fam0entry5);
        $fam0entry9->addExcludedEntry($fam0entry6);
        $fam0entry9->addExcludedEntry($fam0entry7);
        $fam0entry9->addExcludedEntry($fam0entry8);

        $fam1entry0->addExcludedEntry($fam1entry1);
        $fam1entry0->addExcludedEntry($fam1entry2);
        $fam1entry0->addExcludedEntry($fam1entry3);
        $fam1entry0->addExcludedEntry($fam1entry4);
        $fam1entry0->addExcludedEntry($fam1entry5);
        $fam1entry0->addExcludedEntry($fam1entry6);
        $fam1entry0->addExcludedEntry($fam1entry7);
        $fam1entry0->addExcludedEntry($fam1entry8);
        $fam1entry0->addExcludedEntry($fam1entry9);
        $fam1entry1->addExcludedEntry($fam1entry0);
        $fam1entry1->addExcludedEntry($fam1entry2);
        $fam1entry1->addExcludedEntry($fam1entry3);
        $fam1entry1->addExcludedEntry($fam1entry4);
        $fam1entry1->addExcludedEntry($fam1entry5);
        $fam1entry1->addExcludedEntry($fam1entry6);
        $fam1entry1->addExcludedEntry($fam1entry7);
        $fam1entry1->addExcludedEntry($fam1entry8);
        $fam1entry1->addExcludedEntry($fam1entry9);
        $fam1entry2->addExcludedEntry($fam1entry0);
        $fam1entry2->addExcludedEntry($fam1entry1);
        $fam1entry2->addExcludedEntry($fam1entry3);
        $fam1entry2->addExcludedEntry($fam1entry4);
        $fam1entry2->addExcludedEntry($fam1entry5);
        $fam1entry2->addExcludedEntry($fam1entry6);
        $fam1entry2->addExcludedEntry($fam1entry7);
        $fam1entry2->addExcludedEntry($fam1entry8);
        $fam1entry2->addExcludedEntry($fam1entry9);
        $fam1entry3->addExcludedEntry($fam1entry0);
        $fam1entry3->addExcludedEntry($fam1entry1);
        $fam1entry3->addExcludedEntry($fam1entry2);
        $fam1entry3->addExcludedEntry($fam1entry4);
        $fam1entry3->addExcludedEntry($fam1entry5);
        $fam1entry3->addExcludedEntry($fam1entry6);
        $fam1entry3->addExcludedEntry($fam1entry7);
        $fam1entry3->addExcludedEntry($fam1entry8);
        $fam1entry3->addExcludedEntry($fam1entry9);
        $fam1entry4->addExcludedEntry($fam1entry0);
        $fam1entry4->addExcludedEntry($fam1entry1);
        $fam1entry4->addExcludedEntry($fam1entry2);
        $fam1entry4->addExcludedEntry($fam1entry3);
        $fam1entry4->addExcludedEntry($fam1entry5);
        $fam1entry4->addExcludedEntry($fam1entry6);
        $fam1entry4->addExcludedEntry($fam1entry7);
        $fam1entry4->addExcludedEntry($fam1entry8);
        $fam1entry4->addExcludedEntry($fam1entry9);
        $fam1entry5->addExcludedEntry($fam1entry0);
        $fam1entry5->addExcludedEntry($fam1entry1);
        $fam1entry5->addExcludedEntry($fam1entry2);
        $fam1entry5->addExcludedEntry($fam1entry3);
        $fam1entry5->addExcludedEntry($fam1entry4);
        $fam1entry5->addExcludedEntry($fam1entry6);
        $fam1entry5->addExcludedEntry($fam1entry7);
        $fam1entry5->addExcludedEntry($fam1entry8);
        $fam1entry5->addExcludedEntry($fam1entry9);
        $fam1entry6->addExcludedEntry($fam1entry0);
        $fam1entry6->addExcludedEntry($fam1entry1);
        $fam1entry6->addExcludedEntry($fam1entry2);
        $fam1entry6->addExcludedEntry($fam1entry3);
        $fam1entry6->addExcludedEntry($fam1entry4);
        $fam1entry6->addExcludedEntry($fam1entry5);
        $fam1entry6->addExcludedEntry($fam1entry7);
        $fam1entry6->addExcludedEntry($fam1entry8);
        $fam1entry6->addExcludedEntry($fam1entry9);
        $fam1entry7->addExcludedEntry($fam1entry0);
        $fam1entry7->addExcludedEntry($fam1entry1);
        $fam1entry7->addExcludedEntry($fam1entry2);
        $fam1entry7->addExcludedEntry($fam1entry3);
        $fam1entry7->addExcludedEntry($fam1entry4);
        $fam1entry7->addExcludedEntry($fam1entry5);
        $fam1entry7->addExcludedEntry($fam1entry6);
        $fam1entry7->addExcludedEntry($fam1entry8);
        $fam1entry7->addExcludedEntry($fam1entry9);
        $fam1entry8->addExcludedEntry($fam1entry0);
        $fam1entry8->addExcludedEntry($fam1entry1);
        $fam1entry8->addExcludedEntry($fam1entry2);
        $fam1entry8->addExcludedEntry($fam1entry3);
        $fam1entry8->addExcludedEntry($fam1entry4);
        $fam1entry8->addExcludedEntry($fam1entry5);
        $fam1entry8->addExcludedEntry($fam1entry6);
        $fam1entry8->addExcludedEntry($fam1entry7);
        $fam1entry8->addExcludedEntry($fam1entry9);
        $fam1entry9->addExcludedEntry($fam1entry0);
        $fam1entry9->addExcludedEntry($fam1entry1);
        $fam1entry9->addExcludedEntry($fam1entry2);
        $fam1entry9->addExcludedEntry($fam1entry3);
        $fam1entry9->addExcludedEntry($fam1entry4);
        $fam1entry9->addExcludedEntry($fam1entry5);
        $fam1entry9->addExcludedEntry($fam1entry6);
        $fam1entry9->addExcludedEntry($fam1entry7);
        $fam1entry9->addExcludedEntry($fam1entry8);

        $fam2entry0->addExcludedEntry($fam2entry1);
        $fam2entry0->addExcludedEntry($fam2entry2);
        $fam2entry0->addExcludedEntry($fam2entry3);
        $fam2entry0->addExcludedEntry($fam2entry4);
        $fam2entry0->addExcludedEntry($fam2entry5);
        $fam2entry0->addExcludedEntry($fam2entry6);
        $fam2entry0->addExcludedEntry($fam2entry7);
        $fam2entry0->addExcludedEntry($fam2entry8);
        $fam2entry0->addExcludedEntry($fam2entry9);
        $fam2entry1->addExcludedEntry($fam2entry0);
        $fam2entry1->addExcludedEntry($fam2entry2);
        $fam2entry1->addExcludedEntry($fam2entry3);
        $fam2entry1->addExcludedEntry($fam2entry4);
        $fam2entry1->addExcludedEntry($fam2entry5);
        $fam2entry1->addExcludedEntry($fam2entry6);
        $fam2entry1->addExcludedEntry($fam2entry7);
        $fam2entry1->addExcludedEntry($fam2entry8);
        $fam2entry1->addExcludedEntry($fam2entry9);
        $fam2entry2->addExcludedEntry($fam2entry0);
        $fam2entry2->addExcludedEntry($fam2entry1);
        $fam2entry2->addExcludedEntry($fam2entry3);
        $fam2entry2->addExcludedEntry($fam2entry4);
        $fam2entry2->addExcludedEntry($fam2entry5);
        $fam2entry2->addExcludedEntry($fam2entry6);
        $fam2entry2->addExcludedEntry($fam2entry7);
        $fam2entry2->addExcludedEntry($fam2entry8);
        $fam2entry2->addExcludedEntry($fam2entry9);
        $fam2entry3->addExcludedEntry($fam2entry0);
        $fam2entry3->addExcludedEntry($fam2entry1);
        $fam2entry3->addExcludedEntry($fam2entry2);
        $fam2entry3->addExcludedEntry($fam2entry4);
        $fam2entry3->addExcludedEntry($fam2entry5);
        $fam2entry3->addExcludedEntry($fam2entry6);
        $fam2entry3->addExcludedEntry($fam2entry7);
        $fam2entry3->addExcludedEntry($fam2entry8);
        $fam2entry3->addExcludedEntry($fam2entry9);
        $fam2entry4->addExcludedEntry($fam2entry0);
        $fam2entry4->addExcludedEntry($fam2entry1);
        $fam2entry4->addExcludedEntry($fam2entry2);
        $fam2entry4->addExcludedEntry($fam2entry3);
        $fam2entry4->addExcludedEntry($fam2entry5);
        $fam2entry4->addExcludedEntry($fam2entry6);
        $fam2entry4->addExcludedEntry($fam2entry7);
        $fam2entry4->addExcludedEntry($fam2entry8);
        $fam2entry4->addExcludedEntry($fam2entry9);
        $fam2entry5->addExcludedEntry($fam2entry0);
        $fam2entry5->addExcludedEntry($fam2entry1);
        $fam2entry5->addExcludedEntry($fam2entry2);
        $fam2entry5->addExcludedEntry($fam2entry3);
        $fam2entry5->addExcludedEntry($fam2entry4);
        $fam2entry5->addExcludedEntry($fam2entry6);
        $fam2entry5->addExcludedEntry($fam2entry7);
        $fam2entry5->addExcludedEntry($fam2entry8);
        $fam2entry5->addExcludedEntry($fam2entry9);
        $fam2entry6->addExcludedEntry($fam2entry0);
        $fam2entry6->addExcludedEntry($fam2entry1);
        $fam2entry6->addExcludedEntry($fam2entry2);
        $fam2entry6->addExcludedEntry($fam2entry3);
        $fam2entry6->addExcludedEntry($fam2entry4);
        $fam2entry6->addExcludedEntry($fam2entry5);
        $fam2entry6->addExcludedEntry($fam2entry7);
        $fam2entry6->addExcludedEntry($fam2entry8);
        $fam2entry6->addExcludedEntry($fam2entry9);
        $fam2entry7->addExcludedEntry($fam2entry0);
        $fam2entry7->addExcludedEntry($fam2entry1);
        $fam2entry7->addExcludedEntry($fam2entry2);
        $fam2entry7->addExcludedEntry($fam2entry3);
        $fam2entry7->addExcludedEntry($fam2entry4);
        $fam2entry7->addExcludedEntry($fam2entry5);
        $fam2entry7->addExcludedEntry($fam2entry6);
        $fam2entry7->addExcludedEntry($fam2entry8);
        $fam2entry7->addExcludedEntry($fam2entry9);
        $fam2entry8->addExcludedEntry($fam2entry0);
        $fam2entry8->addExcludedEntry($fam2entry1);
        $fam2entry8->addExcludedEntry($fam2entry2);
        $fam2entry8->addExcludedEntry($fam2entry3);
        $fam2entry8->addExcludedEntry($fam2entry4);
        $fam2entry8->addExcludedEntry($fam2entry5);
        $fam2entry8->addExcludedEntry($fam2entry6);
        $fam2entry8->addExcludedEntry($fam2entry7);
        $fam2entry8->addExcludedEntry($fam2entry9);
        $fam2entry9->addExcludedEntry($fam2entry0);
        $fam2entry9->addExcludedEntry($fam2entry1);
        $fam2entry9->addExcludedEntry($fam2entry2);
        $fam2entry9->addExcludedEntry($fam2entry3);
        $fam2entry9->addExcludedEntry($fam2entry4);
        $fam2entry9->addExcludedEntry($fam2entry5);
        $fam2entry9->addExcludedEntry($fam2entry6);
        $fam2entry9->addExcludedEntry($fam2entry7);
        $fam2entry9->addExcludedEntry($fam2entry8);

        $fam3entry0->addExcludedEntry($fam3entry1);
        $fam3entry0->addExcludedEntry($fam3entry2);
        $fam3entry0->addExcludedEntry($fam3entry3);
        $fam3entry0->addExcludedEntry($fam3entry4);
        $fam3entry0->addExcludedEntry($fam3entry5);
        $fam3entry0->addExcludedEntry($fam3entry6);
        $fam3entry0->addExcludedEntry($fam3entry7);
        $fam3entry0->addExcludedEntry($fam3entry8);
        $fam3entry0->addExcludedEntry($fam3entry9);
        $fam3entry1->addExcludedEntry($fam3entry0);
        $fam3entry1->addExcludedEntry($fam3entry2);
        $fam3entry1->addExcludedEntry($fam3entry3);
        $fam3entry1->addExcludedEntry($fam3entry4);
        $fam3entry1->addExcludedEntry($fam3entry5);
        $fam3entry1->addExcludedEntry($fam3entry6);
        $fam3entry1->addExcludedEntry($fam3entry7);
        $fam3entry1->addExcludedEntry($fam3entry8);
        $fam3entry1->addExcludedEntry($fam3entry9);
        $fam3entry2->addExcludedEntry($fam3entry0);
        $fam3entry2->addExcludedEntry($fam3entry1);
        $fam3entry2->addExcludedEntry($fam3entry3);
        $fam3entry2->addExcludedEntry($fam3entry4);
        $fam3entry2->addExcludedEntry($fam3entry5);
        $fam3entry2->addExcludedEntry($fam3entry6);
        $fam3entry2->addExcludedEntry($fam3entry7);
        $fam3entry2->addExcludedEntry($fam3entry8);
        $fam3entry2->addExcludedEntry($fam3entry9);
        $fam3entry3->addExcludedEntry($fam3entry0);
        $fam3entry3->addExcludedEntry($fam3entry1);
        $fam3entry3->addExcludedEntry($fam3entry2);
        $fam3entry3->addExcludedEntry($fam3entry4);
        $fam3entry3->addExcludedEntry($fam3entry5);
        $fam3entry3->addExcludedEntry($fam3entry6);
        $fam3entry3->addExcludedEntry($fam3entry7);
        $fam3entry3->addExcludedEntry($fam3entry8);
        $fam3entry3->addExcludedEntry($fam3entry9);
        $fam3entry4->addExcludedEntry($fam3entry0);
        $fam3entry4->addExcludedEntry($fam3entry1);
        $fam3entry4->addExcludedEntry($fam3entry2);
        $fam3entry4->addExcludedEntry($fam3entry3);
        $fam3entry4->addExcludedEntry($fam3entry5);
        $fam3entry4->addExcludedEntry($fam3entry6);
        $fam3entry4->addExcludedEntry($fam3entry7);
        $fam3entry4->addExcludedEntry($fam3entry8);
        $fam3entry4->addExcludedEntry($fam3entry9);
        $fam3entry5->addExcludedEntry($fam3entry0);
        $fam3entry5->addExcludedEntry($fam3entry1);
        $fam3entry5->addExcludedEntry($fam3entry2);
        $fam3entry5->addExcludedEntry($fam3entry3);
        $fam3entry5->addExcludedEntry($fam3entry4);
        $fam3entry5->addExcludedEntry($fam3entry6);
        $fam3entry5->addExcludedEntry($fam3entry7);
        $fam3entry5->addExcludedEntry($fam3entry8);
        $fam3entry5->addExcludedEntry($fam3entry9);
        $fam3entry6->addExcludedEntry($fam3entry0);
        $fam3entry6->addExcludedEntry($fam3entry1);
        $fam3entry6->addExcludedEntry($fam3entry2);
        $fam3entry6->addExcludedEntry($fam3entry3);
        $fam3entry6->addExcludedEntry($fam3entry4);
        $fam3entry6->addExcludedEntry($fam3entry5);
        $fam3entry6->addExcludedEntry($fam3entry7);
        $fam3entry6->addExcludedEntry($fam3entry8);
        $fam3entry6->addExcludedEntry($fam3entry9);
        $fam3entry7->addExcludedEntry($fam3entry0);
        $fam3entry7->addExcludedEntry($fam3entry1);
        $fam3entry7->addExcludedEntry($fam3entry2);
        $fam3entry7->addExcludedEntry($fam3entry3);
        $fam3entry7->addExcludedEntry($fam3entry4);
        $fam3entry7->addExcludedEntry($fam3entry5);
        $fam3entry7->addExcludedEntry($fam3entry6);
        $fam3entry7->addExcludedEntry($fam3entry8);
        $fam3entry7->addExcludedEntry($fam3entry9);
        $fam3entry8->addExcludedEntry($fam3entry0);
        $fam3entry8->addExcludedEntry($fam3entry1);
        $fam3entry8->addExcludedEntry($fam3entry2);
        $fam3entry8->addExcludedEntry($fam3entry3);
        $fam3entry8->addExcludedEntry($fam3entry4);
        $fam3entry8->addExcludedEntry($fam3entry5);
        $fam3entry8->addExcludedEntry($fam3entry6);
        $fam3entry8->addExcludedEntry($fam3entry7);
        $fam3entry8->addExcludedEntry($fam3entry9);
        $fam3entry9->addExcludedEntry($fam3entry0);
        $fam3entry9->addExcludedEntry($fam3entry1);
        $fam3entry9->addExcludedEntry($fam3entry2);
        $fam3entry9->addExcludedEntry($fam3entry3);
        $fam3entry9->addExcludedEntry($fam3entry4);
        $fam3entry9->addExcludedEntry($fam3entry5);
        $fam3entry9->addExcludedEntry($fam3entry6);
        $fam3entry9->addExcludedEntry($fam3entry7);
        $fam3entry9->addExcludedEntry($fam3entry8);

        $fam4entry0->addExcludedEntry($fam4entry1);
        $fam4entry0->addExcludedEntry($fam4entry2);
        $fam4entry0->addExcludedEntry($fam4entry3);
        $fam4entry0->addExcludedEntry($fam4entry4);
        $fam4entry0->addExcludedEntry($fam4entry5);
        $fam4entry0->addExcludedEntry($fam4entry6);
        $fam4entry0->addExcludedEntry($fam4entry7);
        $fam4entry0->addExcludedEntry($fam4entry8);
        $fam4entry0->addExcludedEntry($fam4entry9);
        $fam4entry1->addExcludedEntry($fam4entry0);
        $fam4entry1->addExcludedEntry($fam4entry2);
        $fam4entry1->addExcludedEntry($fam4entry3);
        $fam4entry1->addExcludedEntry($fam4entry4);
        $fam4entry1->addExcludedEntry($fam4entry5);
        $fam4entry1->addExcludedEntry($fam4entry6);
        $fam4entry1->addExcludedEntry($fam4entry7);
        $fam4entry1->addExcludedEntry($fam4entry8);
        $fam4entry1->addExcludedEntry($fam4entry9);
        $fam4entry2->addExcludedEntry($fam4entry0);
        $fam4entry2->addExcludedEntry($fam4entry1);
        $fam4entry2->addExcludedEntry($fam4entry3);
        $fam4entry2->addExcludedEntry($fam4entry4);
        $fam4entry2->addExcludedEntry($fam4entry5);
        $fam4entry2->addExcludedEntry($fam4entry6);
        $fam4entry2->addExcludedEntry($fam4entry7);
        $fam4entry2->addExcludedEntry($fam4entry8);
        $fam4entry2->addExcludedEntry($fam4entry9);
        $fam4entry3->addExcludedEntry($fam4entry0);
        $fam4entry3->addExcludedEntry($fam4entry1);
        $fam4entry3->addExcludedEntry($fam4entry2);
        $fam4entry3->addExcludedEntry($fam4entry4);
        $fam4entry3->addExcludedEntry($fam4entry5);
        $fam4entry3->addExcludedEntry($fam4entry6);
        $fam4entry3->addExcludedEntry($fam4entry7);
        $fam4entry3->addExcludedEntry($fam4entry8);
        $fam4entry3->addExcludedEntry($fam4entry9);
        $fam4entry4->addExcludedEntry($fam4entry0);
        $fam4entry4->addExcludedEntry($fam4entry1);
        $fam4entry4->addExcludedEntry($fam4entry2);
        $fam4entry4->addExcludedEntry($fam4entry3);
        $fam4entry4->addExcludedEntry($fam4entry5);
        $fam4entry4->addExcludedEntry($fam4entry6);
        $fam4entry4->addExcludedEntry($fam4entry7);
        $fam4entry4->addExcludedEntry($fam4entry8);
        $fam4entry4->addExcludedEntry($fam4entry9);
        $fam4entry5->addExcludedEntry($fam4entry0);
        $fam4entry5->addExcludedEntry($fam4entry1);
        $fam4entry5->addExcludedEntry($fam4entry2);
        $fam4entry5->addExcludedEntry($fam4entry3);
        $fam4entry5->addExcludedEntry($fam4entry4);
        $fam4entry5->addExcludedEntry($fam4entry6);
        $fam4entry5->addExcludedEntry($fam4entry7);
        $fam4entry5->addExcludedEntry($fam4entry8);
        $fam4entry5->addExcludedEntry($fam4entry9);
        $fam4entry6->addExcludedEntry($fam4entry0);
        $fam4entry6->addExcludedEntry($fam4entry1);
        $fam4entry6->addExcludedEntry($fam4entry2);
        $fam4entry6->addExcludedEntry($fam4entry3);
        $fam4entry6->addExcludedEntry($fam4entry4);
        $fam4entry6->addExcludedEntry($fam4entry5);
        $fam4entry6->addExcludedEntry($fam4entry7);
        $fam4entry6->addExcludedEntry($fam4entry8);
        $fam4entry6->addExcludedEntry($fam4entry9);
        $fam4entry7->addExcludedEntry($fam4entry0);
        $fam4entry7->addExcludedEntry($fam4entry1);
        $fam4entry7->addExcludedEntry($fam4entry2);
        $fam4entry7->addExcludedEntry($fam4entry3);
        $fam4entry7->addExcludedEntry($fam4entry4);
        $fam4entry7->addExcludedEntry($fam4entry5);
        $fam4entry7->addExcludedEntry($fam4entry6);
        $fam4entry7->addExcludedEntry($fam4entry8);
        $fam4entry7->addExcludedEntry($fam4entry9);
        $fam4entry8->addExcludedEntry($fam4entry0);
        $fam4entry8->addExcludedEntry($fam4entry1);
        $fam4entry8->addExcludedEntry($fam4entry2);
        $fam4entry8->addExcludedEntry($fam4entry3);
        $fam4entry8->addExcludedEntry($fam4entry4);
        $fam4entry8->addExcludedEntry($fam4entry5);
        $fam4entry8->addExcludedEntry($fam4entry6);
        $fam4entry8->addExcludedEntry($fam4entry7);
        $fam4entry8->addExcludedEntry($fam4entry9);
        $fam4entry9->addExcludedEntry($fam4entry0);
        $fam4entry9->addExcludedEntry($fam4entry1);
        $fam4entry9->addExcludedEntry($fam4entry2);
        $fam4entry9->addExcludedEntry($fam4entry3);
        $fam4entry9->addExcludedEntry($fam4entry4);
        $fam4entry9->addExcludedEntry($fam4entry5);
        $fam4entry9->addExcludedEntry($fam4entry6);
        $fam4entry9->addExcludedEntry($fam4entry7);
        $fam4entry9->addExcludedEntry($fam4entry8);

        $fam5entry0->addExcludedEntry($fam5entry1);
        $fam5entry0->addExcludedEntry($fam5entry2);
        $fam5entry0->addExcludedEntry($fam5entry3);
        $fam5entry0->addExcludedEntry($fam5entry4);
        $fam5entry0->addExcludedEntry($fam5entry5);
        $fam5entry0->addExcludedEntry($fam5entry6);
        $fam5entry0->addExcludedEntry($fam5entry7);
        $fam5entry0->addExcludedEntry($fam5entry8);
        $fam5entry0->addExcludedEntry($fam5entry9);
        $fam5entry1->addExcludedEntry($fam5entry0);
        $fam5entry1->addExcludedEntry($fam5entry2);
        $fam5entry1->addExcludedEntry($fam5entry3);
        $fam5entry1->addExcludedEntry($fam5entry4);
        $fam5entry1->addExcludedEntry($fam5entry5);
        $fam5entry1->addExcludedEntry($fam5entry6);
        $fam5entry1->addExcludedEntry($fam5entry7);
        $fam5entry1->addExcludedEntry($fam5entry8);
        $fam5entry1->addExcludedEntry($fam5entry9);
        $fam5entry2->addExcludedEntry($fam5entry0);
        $fam5entry2->addExcludedEntry($fam5entry1);
        $fam5entry2->addExcludedEntry($fam5entry3);
        $fam5entry2->addExcludedEntry($fam5entry4);
        $fam5entry2->addExcludedEntry($fam5entry5);
        $fam5entry2->addExcludedEntry($fam5entry6);
        $fam5entry2->addExcludedEntry($fam5entry7);
        $fam5entry2->addExcludedEntry($fam5entry8);
        $fam5entry2->addExcludedEntry($fam5entry9);
        $fam5entry3->addExcludedEntry($fam5entry0);
        $fam5entry3->addExcludedEntry($fam5entry1);
        $fam5entry3->addExcludedEntry($fam5entry2);
        $fam5entry3->addExcludedEntry($fam5entry4);
        $fam5entry3->addExcludedEntry($fam5entry5);
        $fam5entry3->addExcludedEntry($fam5entry6);
        $fam5entry3->addExcludedEntry($fam5entry7);
        $fam5entry3->addExcludedEntry($fam5entry8);
        $fam5entry3->addExcludedEntry($fam5entry9);
        $fam5entry4->addExcludedEntry($fam5entry0);
        $fam5entry4->addExcludedEntry($fam5entry1);
        $fam5entry4->addExcludedEntry($fam5entry2);
        $fam5entry4->addExcludedEntry($fam5entry3);
        $fam5entry4->addExcludedEntry($fam5entry5);
        $fam5entry4->addExcludedEntry($fam5entry6);
        $fam5entry4->addExcludedEntry($fam5entry7);
        $fam5entry4->addExcludedEntry($fam5entry8);
        $fam5entry4->addExcludedEntry($fam5entry9);
        $fam5entry5->addExcludedEntry($fam5entry0);
        $fam5entry5->addExcludedEntry($fam5entry1);
        $fam5entry5->addExcludedEntry($fam5entry2);
        $fam5entry5->addExcludedEntry($fam5entry3);
        $fam5entry5->addExcludedEntry($fam5entry4);
        $fam5entry5->addExcludedEntry($fam5entry6);
        $fam5entry5->addExcludedEntry($fam5entry7);
        $fam5entry5->addExcludedEntry($fam5entry8);
        $fam5entry5->addExcludedEntry($fam5entry9);
        $fam5entry6->addExcludedEntry($fam5entry0);
        $fam5entry6->addExcludedEntry($fam5entry1);
        $fam5entry6->addExcludedEntry($fam5entry2);
        $fam5entry6->addExcludedEntry($fam5entry3);
        $fam5entry6->addExcludedEntry($fam5entry4);
        $fam5entry6->addExcludedEntry($fam5entry5);
        $fam5entry6->addExcludedEntry($fam5entry7);
        $fam5entry6->addExcludedEntry($fam5entry8);
        $fam5entry6->addExcludedEntry($fam5entry9);
        $fam5entry7->addExcludedEntry($fam5entry0);
        $fam5entry7->addExcludedEntry($fam5entry1);
        $fam5entry7->addExcludedEntry($fam5entry2);
        $fam5entry7->addExcludedEntry($fam5entry3);
        $fam5entry7->addExcludedEntry($fam5entry4);
        $fam5entry7->addExcludedEntry($fam5entry5);
        $fam5entry7->addExcludedEntry($fam5entry6);
        $fam5entry7->addExcludedEntry($fam5entry8);
        $fam5entry7->addExcludedEntry($fam5entry9);
        $fam5entry8->addExcludedEntry($fam5entry0);
        $fam5entry8->addExcludedEntry($fam5entry1);
        $fam5entry8->addExcludedEntry($fam5entry2);
        $fam5entry8->addExcludedEntry($fam5entry3);
        $fam5entry8->addExcludedEntry($fam5entry4);
        $fam5entry8->addExcludedEntry($fam5entry5);
        $fam5entry8->addExcludedEntry($fam5entry6);
        $fam5entry8->addExcludedEntry($fam5entry7);
        $fam5entry8->addExcludedEntry($fam5entry9);
        $fam5entry9->addExcludedEntry($fam5entry0);
        $fam5entry9->addExcludedEntry($fam5entry1);
        $fam5entry9->addExcludedEntry($fam5entry2);
        $fam5entry9->addExcludedEntry($fam5entry3);
        $fam5entry9->addExcludedEntry($fam5entry4);
        $fam5entry9->addExcludedEntry($fam5entry5);
        $fam5entry9->addExcludedEntry($fam5entry6);
        $fam5entry9->addExcludedEntry($fam5entry7);
        $fam5entry9->addExcludedEntry($fam5entry8);

        $fam6entry0->addExcludedEntry($fam6entry1);
        $fam6entry0->addExcludedEntry($fam6entry2);
        $fam6entry0->addExcludedEntry($fam6entry3);
        $fam6entry0->addExcludedEntry($fam6entry4);
        $fam6entry0->addExcludedEntry($fam6entry5);
        $fam6entry0->addExcludedEntry($fam6entry6);
        $fam6entry0->addExcludedEntry($fam6entry7);
        $fam6entry0->addExcludedEntry($fam6entry8);
        $fam6entry0->addExcludedEntry($fam6entry9);
        $fam6entry1->addExcludedEntry($fam6entry0);
        $fam6entry1->addExcludedEntry($fam6entry2);
        $fam6entry1->addExcludedEntry($fam6entry3);
        $fam6entry1->addExcludedEntry($fam6entry4);
        $fam6entry1->addExcludedEntry($fam6entry5);
        $fam6entry1->addExcludedEntry($fam6entry6);
        $fam6entry1->addExcludedEntry($fam6entry7);
        $fam6entry1->addExcludedEntry($fam6entry8);
        $fam6entry1->addExcludedEntry($fam6entry9);
        $fam6entry2->addExcludedEntry($fam6entry0);
        $fam6entry2->addExcludedEntry($fam6entry1);
        $fam6entry2->addExcludedEntry($fam6entry3);
        $fam6entry2->addExcludedEntry($fam6entry4);
        $fam6entry2->addExcludedEntry($fam6entry5);
        $fam6entry2->addExcludedEntry($fam6entry6);
        $fam6entry2->addExcludedEntry($fam6entry7);
        $fam6entry2->addExcludedEntry($fam6entry8);
        $fam6entry2->addExcludedEntry($fam6entry9);
        $fam6entry3->addExcludedEntry($fam6entry0);
        $fam6entry3->addExcludedEntry($fam6entry1);
        $fam6entry3->addExcludedEntry($fam6entry2);
        $fam6entry3->addExcludedEntry($fam6entry4);
        $fam6entry3->addExcludedEntry($fam6entry5);
        $fam6entry3->addExcludedEntry($fam6entry6);
        $fam6entry3->addExcludedEntry($fam6entry7);
        $fam6entry3->addExcludedEntry($fam6entry8);
        $fam6entry3->addExcludedEntry($fam6entry9);
        $fam6entry4->addExcludedEntry($fam6entry0);
        $fam6entry4->addExcludedEntry($fam6entry1);
        $fam6entry4->addExcludedEntry($fam6entry2);
        $fam6entry4->addExcludedEntry($fam6entry3);
        $fam6entry4->addExcludedEntry($fam6entry5);
        $fam6entry4->addExcludedEntry($fam6entry6);
        $fam6entry4->addExcludedEntry($fam6entry7);
        $fam6entry4->addExcludedEntry($fam6entry8);
        $fam6entry4->addExcludedEntry($fam6entry9);
        $fam6entry5->addExcludedEntry($fam6entry0);
        $fam6entry5->addExcludedEntry($fam6entry1);
        $fam6entry5->addExcludedEntry($fam6entry2);
        $fam6entry5->addExcludedEntry($fam6entry3);
        $fam6entry5->addExcludedEntry($fam6entry4);
        $fam6entry5->addExcludedEntry($fam6entry6);
        $fam6entry5->addExcludedEntry($fam6entry7);
        $fam6entry5->addExcludedEntry($fam6entry8);
        $fam6entry5->addExcludedEntry($fam6entry9);
        $fam6entry6->addExcludedEntry($fam6entry0);
        $fam6entry6->addExcludedEntry($fam6entry1);
        $fam6entry6->addExcludedEntry($fam6entry2);
        $fam6entry6->addExcludedEntry($fam6entry3);
        $fam6entry6->addExcludedEntry($fam6entry4);
        $fam6entry6->addExcludedEntry($fam6entry5);
        $fam6entry6->addExcludedEntry($fam6entry7);
        $fam6entry6->addExcludedEntry($fam6entry8);
        $fam6entry6->addExcludedEntry($fam6entry9);
        $fam6entry7->addExcludedEntry($fam6entry0);
        $fam6entry7->addExcludedEntry($fam6entry1);
        $fam6entry7->addExcludedEntry($fam6entry2);
        $fam6entry7->addExcludedEntry($fam6entry3);
        $fam6entry7->addExcludedEntry($fam6entry4);
        $fam6entry7->addExcludedEntry($fam6entry5);
        $fam6entry7->addExcludedEntry($fam6entry6);
        $fam6entry7->addExcludedEntry($fam6entry8);
        $fam6entry7->addExcludedEntry($fam6entry9);
        $fam6entry8->addExcludedEntry($fam6entry0);
        $fam6entry8->addExcludedEntry($fam6entry1);
        $fam6entry8->addExcludedEntry($fam6entry2);
        $fam6entry8->addExcludedEntry($fam6entry3);
        $fam6entry8->addExcludedEntry($fam6entry4);
        $fam6entry8->addExcludedEntry($fam6entry5);
        $fam6entry8->addExcludedEntry($fam6entry6);
        $fam6entry8->addExcludedEntry($fam6entry7);
        $fam6entry8->addExcludedEntry($fam6entry9);
        $fam6entry9->addExcludedEntry($fam6entry0);
        $fam6entry9->addExcludedEntry($fam6entry1);
        $fam6entry9->addExcludedEntry($fam6entry2);
        $fam6entry9->addExcludedEntry($fam6entry3);
        $fam6entry9->addExcludedEntry($fam6entry4);
        $fam6entry9->addExcludedEntry($fam6entry5);
        $fam6entry9->addExcludedEntry($fam6entry6);
        $fam6entry9->addExcludedEntry($fam6entry7);
        $fam6entry9->addExcludedEntry($fam6entry8);

        $fam7entry0->addExcludedEntry($fam7entry1);
        $fam7entry0->addExcludedEntry($fam7entry2);
        $fam7entry0->addExcludedEntry($fam7entry3);
        $fam7entry0->addExcludedEntry($fam7entry4);
        $fam7entry0->addExcludedEntry($fam7entry5);
        $fam7entry0->addExcludedEntry($fam7entry6);
        $fam7entry0->addExcludedEntry($fam7entry7);
        $fam7entry0->addExcludedEntry($fam7entry8);
        $fam7entry0->addExcludedEntry($fam7entry9);
        $fam7entry1->addExcludedEntry($fam7entry0);
        $fam7entry1->addExcludedEntry($fam7entry2);
        $fam7entry1->addExcludedEntry($fam7entry3);
        $fam7entry1->addExcludedEntry($fam7entry4);
        $fam7entry1->addExcludedEntry($fam7entry5);
        $fam7entry1->addExcludedEntry($fam7entry6);
        $fam7entry1->addExcludedEntry($fam7entry7);
        $fam7entry1->addExcludedEntry($fam7entry8);
        $fam7entry1->addExcludedEntry($fam7entry9);
        $fam7entry2->addExcludedEntry($fam7entry0);
        $fam7entry2->addExcludedEntry($fam7entry1);
        $fam7entry2->addExcludedEntry($fam7entry3);
        $fam7entry2->addExcludedEntry($fam7entry4);
        $fam7entry2->addExcludedEntry($fam7entry5);
        $fam7entry2->addExcludedEntry($fam7entry6);
        $fam7entry2->addExcludedEntry($fam7entry7);
        $fam7entry2->addExcludedEntry($fam7entry8);
        $fam7entry2->addExcludedEntry($fam7entry9);
        $fam7entry3->addExcludedEntry($fam7entry0);
        $fam7entry3->addExcludedEntry($fam7entry1);
        $fam7entry3->addExcludedEntry($fam7entry2);
        $fam7entry3->addExcludedEntry($fam7entry4);
        $fam7entry3->addExcludedEntry($fam7entry5);
        $fam7entry3->addExcludedEntry($fam7entry6);
        $fam7entry3->addExcludedEntry($fam7entry7);
        $fam7entry3->addExcludedEntry($fam7entry8);
        $fam7entry3->addExcludedEntry($fam7entry9);
        $fam7entry4->addExcludedEntry($fam7entry0);
        $fam7entry4->addExcludedEntry($fam7entry1);
        $fam7entry4->addExcludedEntry($fam7entry2);
        $fam7entry4->addExcludedEntry($fam7entry3);
        $fam7entry4->addExcludedEntry($fam7entry5);
        $fam7entry4->addExcludedEntry($fam7entry6);
        $fam7entry4->addExcludedEntry($fam7entry7);
        $fam7entry4->addExcludedEntry($fam7entry8);
        $fam7entry4->addExcludedEntry($fam7entry9);
        $fam7entry5->addExcludedEntry($fam7entry0);
        $fam7entry5->addExcludedEntry($fam7entry1);
        $fam7entry5->addExcludedEntry($fam7entry2);
        $fam7entry5->addExcludedEntry($fam7entry3);
        $fam7entry5->addExcludedEntry($fam7entry4);
        $fam7entry5->addExcludedEntry($fam7entry6);
        $fam7entry5->addExcludedEntry($fam7entry7);
        $fam7entry5->addExcludedEntry($fam7entry8);
        $fam7entry5->addExcludedEntry($fam7entry9);
        $fam7entry6->addExcludedEntry($fam7entry0);
        $fam7entry6->addExcludedEntry($fam7entry1);
        $fam7entry6->addExcludedEntry($fam7entry2);
        $fam7entry6->addExcludedEntry($fam7entry3);
        $fam7entry6->addExcludedEntry($fam7entry4);
        $fam7entry6->addExcludedEntry($fam7entry5);
        $fam7entry6->addExcludedEntry($fam7entry7);
        $fam7entry6->addExcludedEntry($fam7entry8);
        $fam7entry6->addExcludedEntry($fam7entry9);
        $fam7entry7->addExcludedEntry($fam7entry0);
        $fam7entry7->addExcludedEntry($fam7entry1);
        $fam7entry7->addExcludedEntry($fam7entry2);
        $fam7entry7->addExcludedEntry($fam7entry3);
        $fam7entry7->addExcludedEntry($fam7entry4);
        $fam7entry7->addExcludedEntry($fam7entry5);
        $fam7entry7->addExcludedEntry($fam7entry6);
        $fam7entry7->addExcludedEntry($fam7entry8);
        $fam7entry7->addExcludedEntry($fam7entry9);
        $fam7entry8->addExcludedEntry($fam7entry0);
        $fam7entry8->addExcludedEntry($fam7entry1);
        $fam7entry8->addExcludedEntry($fam7entry2);
        $fam7entry8->addExcludedEntry($fam7entry3);
        $fam7entry8->addExcludedEntry($fam7entry4);
        $fam7entry8->addExcludedEntry($fam7entry5);
        $fam7entry8->addExcludedEntry($fam7entry6);
        $fam7entry8->addExcludedEntry($fam7entry7);
        $fam7entry8->addExcludedEntry($fam7entry9);
        $fam7entry9->addExcludedEntry($fam7entry0);
        $fam7entry9->addExcludedEntry($fam7entry1);
        $fam7entry9->addExcludedEntry($fam7entry2);
        $fam7entry9->addExcludedEntry($fam7entry3);
        $fam7entry9->addExcludedEntry($fam7entry4);
        $fam7entry9->addExcludedEntry($fam7entry5);
        $fam7entry9->addExcludedEntry($fam7entry6);
        $fam7entry9->addExcludedEntry($fam7entry7);
        $fam7entry9->addExcludedEntry($fam7entry8);

        $fam8entry0->addExcludedEntry($fam8entry1);
        $fam8entry0->addExcludedEntry($fam8entry2);
        $fam8entry0->addExcludedEntry($fam8entry3);
        $fam8entry0->addExcludedEntry($fam8entry4);
        $fam8entry0->addExcludedEntry($fam8entry5);
        $fam8entry0->addExcludedEntry($fam8entry6);
        $fam8entry0->addExcludedEntry($fam8entry7);
        $fam8entry0->addExcludedEntry($fam8entry8);
        $fam8entry0->addExcludedEntry($fam8entry9);
        $fam8entry1->addExcludedEntry($fam8entry0);
        $fam8entry1->addExcludedEntry($fam8entry2);
        $fam8entry1->addExcludedEntry($fam8entry3);
        $fam8entry1->addExcludedEntry($fam8entry4);
        $fam8entry1->addExcludedEntry($fam8entry5);
        $fam8entry1->addExcludedEntry($fam8entry6);
        $fam8entry1->addExcludedEntry($fam8entry7);
        $fam8entry1->addExcludedEntry($fam8entry8);
        $fam8entry1->addExcludedEntry($fam8entry9);
        $fam8entry2->addExcludedEntry($fam8entry0);
        $fam8entry2->addExcludedEntry($fam8entry1);
        $fam8entry2->addExcludedEntry($fam8entry3);
        $fam8entry2->addExcludedEntry($fam8entry4);
        $fam8entry2->addExcludedEntry($fam8entry5);
        $fam8entry2->addExcludedEntry($fam8entry6);
        $fam8entry2->addExcludedEntry($fam8entry7);
        $fam8entry2->addExcludedEntry($fam8entry8);
        $fam8entry2->addExcludedEntry($fam8entry9);
        $fam8entry3->addExcludedEntry($fam8entry0);
        $fam8entry3->addExcludedEntry($fam8entry1);
        $fam8entry3->addExcludedEntry($fam8entry2);
        $fam8entry3->addExcludedEntry($fam8entry4);
        $fam8entry3->addExcludedEntry($fam8entry5);
        $fam8entry3->addExcludedEntry($fam8entry6);
        $fam8entry3->addExcludedEntry($fam8entry7);
        $fam8entry3->addExcludedEntry($fam8entry8);
        $fam8entry3->addExcludedEntry($fam8entry9);
        $fam8entry4->addExcludedEntry($fam8entry0);
        $fam8entry4->addExcludedEntry($fam8entry1);
        $fam8entry4->addExcludedEntry($fam8entry2);
        $fam8entry4->addExcludedEntry($fam8entry3);
        $fam8entry4->addExcludedEntry($fam8entry5);
        $fam8entry4->addExcludedEntry($fam8entry6);
        $fam8entry4->addExcludedEntry($fam8entry7);
        $fam8entry4->addExcludedEntry($fam8entry8);
        $fam8entry4->addExcludedEntry($fam8entry9);
        $fam8entry5->addExcludedEntry($fam8entry0);
        $fam8entry5->addExcludedEntry($fam8entry1);
        $fam8entry5->addExcludedEntry($fam8entry2);
        $fam8entry5->addExcludedEntry($fam8entry3);
        $fam8entry5->addExcludedEntry($fam8entry4);
        $fam8entry5->addExcludedEntry($fam8entry6);
        $fam8entry5->addExcludedEntry($fam8entry7);
        $fam8entry5->addExcludedEntry($fam8entry8);
        $fam8entry5->addExcludedEntry($fam8entry9);
        $fam8entry6->addExcludedEntry($fam8entry0);
        $fam8entry6->addExcludedEntry($fam8entry1);
        $fam8entry6->addExcludedEntry($fam8entry2);
        $fam8entry6->addExcludedEntry($fam8entry3);
        $fam8entry6->addExcludedEntry($fam8entry4);
        $fam8entry6->addExcludedEntry($fam8entry5);
        $fam8entry6->addExcludedEntry($fam8entry7);
        $fam8entry6->addExcludedEntry($fam8entry8);
        $fam8entry6->addExcludedEntry($fam8entry9);
        $fam8entry7->addExcludedEntry($fam8entry0);
        $fam8entry7->addExcludedEntry($fam8entry1);
        $fam8entry7->addExcludedEntry($fam8entry2);
        $fam8entry7->addExcludedEntry($fam8entry3);
        $fam8entry7->addExcludedEntry($fam8entry4);
        $fam8entry7->addExcludedEntry($fam8entry5);
        $fam8entry7->addExcludedEntry($fam8entry6);
        $fam8entry7->addExcludedEntry($fam8entry8);
        $fam8entry7->addExcludedEntry($fam8entry9);
        $fam8entry8->addExcludedEntry($fam8entry0);
        $fam8entry8->addExcludedEntry($fam8entry1);
        $fam8entry8->addExcludedEntry($fam8entry2);
        $fam8entry8->addExcludedEntry($fam8entry3);
        $fam8entry8->addExcludedEntry($fam8entry4);
        $fam8entry8->addExcludedEntry($fam8entry5);
        $fam8entry8->addExcludedEntry($fam8entry6);
        $fam8entry8->addExcludedEntry($fam8entry7);
        $fam8entry8->addExcludedEntry($fam8entry9);
        $fam8entry9->addExcludedEntry($fam8entry0);
        $fam8entry9->addExcludedEntry($fam8entry1);
        $fam8entry9->addExcludedEntry($fam8entry2);
        $fam8entry9->addExcludedEntry($fam8entry3);
        $fam8entry9->addExcludedEntry($fam8entry4);
        $fam8entry9->addExcludedEntry($fam8entry5);
        $fam8entry9->addExcludedEntry($fam8entry6);
        $fam8entry9->addExcludedEntry($fam8entry7);
        $fam8entry9->addExcludedEntry($fam8entry8);

        $fam9entry0->addExcludedEntry($fam9entry1);
        $fam9entry0->addExcludedEntry($fam9entry2);
        $fam9entry0->addExcludedEntry($fam9entry3);
        $fam9entry0->addExcludedEntry($fam9entry4);
        $fam9entry0->addExcludedEntry($fam9entry5);
        $fam9entry0->addExcludedEntry($fam9entry6);
        $fam9entry0->addExcludedEntry($fam9entry7);
        $fam9entry0->addExcludedEntry($fam9entry8);
        $fam9entry0->addExcludedEntry($fam9entry9);
        $fam9entry1->addExcludedEntry($fam9entry0);
        $fam9entry1->addExcludedEntry($fam9entry2);
        $fam9entry1->addExcludedEntry($fam9entry3);
        $fam9entry1->addExcludedEntry($fam9entry4);
        $fam9entry1->addExcludedEntry($fam9entry5);
        $fam9entry1->addExcludedEntry($fam9entry6);
        $fam9entry1->addExcludedEntry($fam9entry7);
        $fam9entry1->addExcludedEntry($fam9entry8);
        $fam9entry1->addExcludedEntry($fam9entry9);
        $fam9entry2->addExcludedEntry($fam9entry0);
        $fam9entry2->addExcludedEntry($fam9entry1);
        $fam9entry2->addExcludedEntry($fam9entry3);
        $fam9entry2->addExcludedEntry($fam9entry4);
        $fam9entry2->addExcludedEntry($fam9entry5);
        $fam9entry2->addExcludedEntry($fam9entry6);
        $fam9entry2->addExcludedEntry($fam9entry7);
        $fam9entry2->addExcludedEntry($fam9entry8);
        $fam9entry2->addExcludedEntry($fam9entry9);
        $fam9entry3->addExcludedEntry($fam9entry0);
        $fam9entry3->addExcludedEntry($fam9entry1);
        $fam9entry3->addExcludedEntry($fam9entry2);
        $fam9entry3->addExcludedEntry($fam9entry4);
        $fam9entry3->addExcludedEntry($fam9entry5);
        $fam9entry3->addExcludedEntry($fam9entry6);
        $fam9entry3->addExcludedEntry($fam9entry7);
        $fam9entry3->addExcludedEntry($fam9entry8);
        $fam9entry3->addExcludedEntry($fam9entry9);
        $fam9entry4->addExcludedEntry($fam9entry0);
        $fam9entry4->addExcludedEntry($fam9entry1);
        $fam9entry4->addExcludedEntry($fam9entry2);
        $fam9entry4->addExcludedEntry($fam9entry3);
        $fam9entry4->addExcludedEntry($fam9entry5);
        $fam9entry4->addExcludedEntry($fam9entry6);
        $fam9entry4->addExcludedEntry($fam9entry7);
        $fam9entry4->addExcludedEntry($fam9entry8);
        $fam9entry4->addExcludedEntry($fam9entry9);
        $fam9entry5->addExcludedEntry($fam9entry0);
        $fam9entry5->addExcludedEntry($fam9entry1);
        $fam9entry5->addExcludedEntry($fam9entry2);
        $fam9entry5->addExcludedEntry($fam9entry3);
        $fam9entry5->addExcludedEntry($fam9entry4);
        $fam9entry5->addExcludedEntry($fam9entry6);
        $fam9entry5->addExcludedEntry($fam9entry7);
        $fam9entry5->addExcludedEntry($fam9entry8);
        $fam9entry5->addExcludedEntry($fam9entry9);
        $fam9entry6->addExcludedEntry($fam9entry0);
        $fam9entry6->addExcludedEntry($fam9entry1);
        $fam9entry6->addExcludedEntry($fam9entry2);
        $fam9entry6->addExcludedEntry($fam9entry3);
        $fam9entry6->addExcludedEntry($fam9entry4);
        $fam9entry6->addExcludedEntry($fam9entry5);
        $fam9entry6->addExcludedEntry($fam9entry7);
        $fam9entry6->addExcludedEntry($fam9entry8);
        $fam9entry6->addExcludedEntry($fam9entry9);
        $fam9entry7->addExcludedEntry($fam9entry0);
        $fam9entry7->addExcludedEntry($fam9entry1);
        $fam9entry7->addExcludedEntry($fam9entry2);
        $fam9entry7->addExcludedEntry($fam9entry3);
        $fam9entry7->addExcludedEntry($fam9entry4);
        $fam9entry7->addExcludedEntry($fam9entry5);
        $fam9entry7->addExcludedEntry($fam9entry6);
        $fam9entry7->addExcludedEntry($fam9entry8);
        $fam9entry7->addExcludedEntry($fam9entry9);
        $fam9entry8->addExcludedEntry($fam9entry0);
        $fam9entry8->addExcludedEntry($fam9entry1);
        $fam9entry8->addExcludedEntry($fam9entry2);
        $fam9entry8->addExcludedEntry($fam9entry3);
        $fam9entry8->addExcludedEntry($fam9entry4);
        $fam9entry8->addExcludedEntry($fam9entry5);
        $fam9entry8->addExcludedEntry($fam9entry6);
        $fam9entry8->addExcludedEntry($fam9entry7);
        $fam9entry8->addExcludedEntry($fam9entry9);
        $fam9entry9->addExcludedEntry($fam9entry0);
        $fam9entry9->addExcludedEntry($fam9entry1);
        $fam9entry9->addExcludedEntry($fam9entry2);
        $fam9entry9->addExcludedEntry($fam9entry3);
        $fam9entry9->addExcludedEntry($fam9entry4);
        $fam9entry9->addExcludedEntry($fam9entry5);
        $fam9entry9->addExcludedEntry($fam9entry6);
        $fam9entry9->addExcludedEntry($fam9entry7);
        $fam9entry9->addExcludedEntry($fam9entry8);

        $entryShuffler = new EntryShuffler();
        for ($i = 0; $i < 1000; $i++) {
            $shuffeledEntries = $entryShuffler->shuffleEntries($pool);

            $key = 0;
            foreach ($pool->getEntries() as $entry) {
                //check if we did not match excluded entry
                $this->assertNotContains($shuffeledEntries[$key], $entry->getExcludedEntries());
                //check if we have an entry matched
                $this->assertNotNull($shuffeledEntries[$key]);
                $key++;
            }
        }
    }
}
