FROM php:7.4.0RC3-fpm-alpine
RUN apk add --no-cache git mysql-client curl autoconf icu-libs && \
    apk add --no-cache --virtual build-dependencies icu-dev libxml2-dev freetype-dev libpng-dev libjpeg-turbo-dev g++ make autoconf
RUN docker-php-ext-install pdo pdo_mysql bcmath intl
RUN docker-php-source extract \
    && docker-php-source delete
RUN apk del build-dependencies
