<?php

namespace Intracto\SecretSantaBundle\Query;

class Languages
{
    public static $list = [
            'en' => 'english',
            'ga' => 'english',
            'cy' => 'english',
            'es' => 'spanish',
            'ca' => 'spanish',
            'gl' => 'spanish',
            'eu' => 'spanish',
            'nl' => 'dutch',
            'fr' => 'french',
            'br' => 'french',
            'ru' => 'russian',
            'pt' => 'portuguese',
            'de' => 'german',
            'zh' => 'chinese',
            'ko' => 'korean',
            'ro' => 'romanian',
            'it' => 'italian',
            'uk' => 'ukrainian',
            'sv' => 'swedish',
            'pl' => 'polish',
            'ja' => 'japanese',
            'el' => 'greek',
            'tr' => 'turkish',
            'bg' => 'bulgarian',
            'vi' => 'vietnamese',
            'nb' => 'norwegian',
            'no' => 'norwegian',
            'da' => 'danish',
            'fi' => 'finnish',
            'hu' => 'hungarian',
            'et' => 'estonian',
            'lt' => 'lithuanian',
            'lv' => 'latvian',
            'sr' => 'serbian',
            'sl' => 'slovene',
            'sk' => 'slovak',
            'hr' => 'croatian',
            'cs' => 'czech',
            'ar' => 'arabic',
            'mt' => 'maltese',
            'th' => 'thai',
            'he' => 'hebrew',
            'bs' => 'bosnian',
            'kk' => 'kazakh',
            'id' => 'indonesian',
            'af' => 'afrikaans',
            'ms' => 'malay',
            'to' => 'tonga',
            'ka' => 'georgian',
            'tl' => 'tagalog',
            'is' => 'icelandic',
            'mn' => 'mongolian',
            'bh' => 'bihari',
            'ak' => 'akan',
            'fa' => 'persian',
            'mi' => 'maori',
            'be' => 'belarusian',
            'gu' => 'gujarati',
            'hi' => 'hindi',
            'lb' => 'luxembourgish',
            'ta' => 'tamil',
            'uz' => 'uzbek',
            'sw' => 'swahili',
            'pa' => 'panjabi',
        ];
}